// Format for state dropdown options
export const usStateOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'AL', label: '阿拉巴马' },
  { value: 'AK', label: '阿拉斯加' },
  { value: 'AS', label: '美属萨摩亚' },
  { value: 'AZ', label: '亚利桑那' },
  { value: 'AR', label: '阿肯色' },
  { value: 'CA', label: '加利福尼亚' },
  { value: 'CO', label: '科罗拉多' },
  { value: 'CT', label: '康涅狄格' },
  { value: 'DE', label: '特拉华' },
  { value: 'DC', label: '哥伦比亚特区' },
  { value: 'FL', label: '佛罗里达' },
  { value: 'GA', label: '乔治亚' },
  { value: 'GU', label: '关岛' },
  { value: 'HI', label: '夏威夷' },
  { value: 'ID', label: '爱达荷' },
  { value: 'IL', label: '伊利诺伊' },
  { value: 'IN', label: '印第安纳' },
  { value: 'IA', label: '爱荷华' },
  { value: 'KS', label: '堪萨斯' },
  { value: 'KY', label: '肯塔基' },
  { value: 'LA', label: '路易斯安那' },
  { value: 'ME', label: '缅因' },
  { value: 'MD', label: '马里兰' },
  { value: 'MA', label: '马萨诸塞' },
  { value: 'MI', label: '密歇根' },
  { value: 'MN', label: '明尼苏达' },
  { value: 'MS', label: '密西西比' },
  { value: 'MO', label: '密苏里' },
  { value: 'MT', label: '蒙大拿' },
  { value: 'NE', label: '内布拉斯加' },
  { value: 'NV', label: '内华达' },
  { value: 'NH', label: '新罕布什尔' },
  { value: 'NJ', label: '新泽西' },
  { value: 'NM', label: '新墨西哥' },
  { value: 'NY', label: '纽约' },
  { value: 'NC', label: '北卡罗来纳' },
  { value: 'ND', label: '北达科他' },
  { value: 'MP', label: '北马里亚纳群岛' },
  { value: 'OH', label: '俄亥俄' },
  { value: 'OK', label: '俄克拉荷马' },
  { value: 'OR', label: '俄勒冈' },
  { value: 'PA', label: '宾夕法尼亚' },
  { value: 'PR', label: '波多黎各' },
  { value: 'RI', label: '罗德岛' },
  { value: 'SC', label: '南卡罗来纳' },
  { value: 'SD', label: '南达科他' },
  { value: 'TN', label: '田纳西' },
  { value: 'TX', label: '德克萨斯' },
  { value: 'UT', label: '犹他' },
  { value: 'VT', label: '佛蒙特' },
  { value: 'VI', label: '美属维尔京群岛' },
  { value: 'VA', label: '弗吉尼亚' },
  { value: 'WA', label: '华盛顿' },
  { value: 'WV', label: '西弗吉尼亚' },
  { value: 'WI', label: '威斯康星' },
  { value: 'WY', label: '怀俄明' },
];

// Format for country dropdown options
export const countryOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'AFGH', label: '阿富汗' },
  { value: 'ALB', label: '阿尔巴尼亚' },
  { value: 'ALGR', label: '阿尔及利亚' },
  { value: 'ASMO', label: '美属萨摩亚' },
  { value: 'ANDO', label: '安道尔' },
  { value: 'ANGL', label: '安哥拉' },
  { value: 'ANGU', label: '安圭拉' },
  { value: 'ANTI', label: '安提瓜和巴布达' },
  { value: 'ARG', label: '阿根廷' },
  { value: 'ARM', label: '亚美尼亚' },
  { value: 'ARB', label: '阿鲁巴' },
  { value: 'XAS', label: '海上' },
  { value: 'ASTL', label: '澳大利亚' },
  { value: 'AUST', label: '奥地利' },
  { value: 'AZR', label: '阿塞拜疆' },
  { value: 'BAMA', label: '巴哈马' },
  { value: 'BAHR', label: '巴林' },
  { value: 'BANG', label: '孟加拉国' },
  { value: 'BRDO', label: '巴巴多斯' },
  { value: 'BYS', label: '白俄罗斯' },
  { value: 'BELG', label: '比利时' },
  { value: 'BLZ', label: '伯利兹' },
  { value: 'BENN', label: '贝宁' },
  { value: 'BERM', label: '百慕大' },
  { value: 'BHU', label: '不丹' },
  { value: 'BOL', label: '玻利维亚' },
  { value: 'BIH', label: '波斯尼亚和黑塞哥维那' },
  { value: 'BOT', label: '博茨瓦纳' },
  { value: 'BRZL', label: '巴西' },
  { value: 'IOT', label: '英属印度洋领地' },
  { value: 'BRNI', label: '文莱' },
  { value: 'BULG', label: '保加利亚' },
  { value: 'BURK', label: '布基纳法索' },
  { value: 'BURM', label: '缅甸' },
  { value: 'BRND', label: '布隆迪' },
  { value: 'CBDA', label: '柬埔寨' },
  { value: 'CMRN', label: '喀麦隆' },
  { value: 'CAN', label: '加拿大' },
  { value: 'CAVI', label: '佛得角' },
  { value: 'CAYI', label: '开曼群岛' },
  { value: 'CAFR', label: '中非共和国' },
  { value: 'CHAD', label: '乍得' },
  { value: 'CHIL', label: '智利' },
  { value: 'CHIN', label: '中国' },
  { value: 'CHRI', label: '圣诞岛' },
  { value: 'COCI', label: '科科斯（基林）群岛' },
  { value: 'COL', label: '哥伦比亚' },
  { value: 'COMO', label: '科摩罗' },
  { value: 'COD', label: '刚果民主共和国' },
  { value: 'CONB', label: '刚果共和国' },
  { value: 'CKIS', label: '库克群岛' },
  { value: 'CSTR', label: '哥斯达黎加' },
  { value: 'IVCO', label: '科特迪瓦' },
  { value: 'HRV', label: '克罗地亚' },
  { value: 'CUBA', label: '古巴' },
  { value: 'CUR', label: '库拉索' },
  { value: 'CYPR', label: '塞浦路斯' },
  { value: 'CZEC', label: '捷克共和国' },
  { value: 'DEN', label: '丹麦' },
  { value: 'DJI', label: '吉布提' },
  { value: 'DOMN', label: '多米尼克' },
  { value: 'DOMR', label: '多米尼加共和国' },
  { value: 'ECUA', label: '厄瓜多尔' },
  { value: 'EGYP', label: '埃及' },
  { value: 'ELSL', label: '萨尔瓦多' },
  { value: 'EGN', label: '赤道几内亚' },
  { value: 'ERI', label: '厄立特里亚' },
  { value: 'EST', label: '爱沙尼亚' },
  { value: 'SZLD', label: '斯威士兰' },
  { value: 'ETH', label: '埃塞俄比亚' },
  { value: 'FKLI', label: '福克兰群岛' },
  { value: 'FRO', label: '法罗群岛' },
  { value: 'FIJI', label: '斐济' },
  { value: 'FIN', label: '芬兰' },
  { value: 'FRAN', label: '法国' },
  { value: 'FPOL', label: '法属波利尼西亚' },
  { value: 'FSAT', label: '法属南部和南极领地' },
  { value: 'GABN', label: '加蓬' },
  { value: 'GAM', label: '冈比亚' },
  { value: 'XGZ', label: '加沙地带' },
  { value: 'GEO', label: '格鲁吉亚' },
  { value: 'GER', label: '德国' },
  { value: 'GHAN', label: '加纳' },
  { value: 'GIB', label: '直布罗陀' },
  { value: 'GRC', label: '希腊' },
  { value: 'GRLD', label: '格陵兰' },
  { value: 'GREN', label: '格林纳达' },
  { value: 'GUAM', label: '关岛' },
  { value: 'GUAT', label: '危地马拉' },
  { value: 'GNEA', label: '几内亚' },
  { value: 'GUIB', label: '几内亚比绍' },
  { value: 'GUY', label: '圭亚那' },
  { value: 'HAT', label: '海地' },
  { value: 'HMD', label: '赫德岛和麦克唐纳群岛' },
  { value: 'VAT', label: '梵蒂冈' },
  { value: 'HOND', label: '洪都拉斯' },
  { value: 'HOKO', label: '香港英国国民(海外)' },
  { value: 'HNK', label: '中国香港特别行政区' },
  { value: 'XHI', label: '豪兰岛' },
  { value: 'HUNG', label: '匈牙利' },
  { value: 'ICLD', label: '冰岛' },
  { value: 'XIR', label: '空中' },
  { value: 'IND', label: '印度' },
  { value: 'IDSA', label: '印度尼西亚' },
  { value: 'IRAN', label: '伊朗' },
  { value: 'IRAQ', label: '伊拉克' },
  { value: 'IRE', label: '爱尔兰' },
  { value: 'ISRL', label: '以色列' },
  { value: 'ITLY', label: '意大利' },
  { value: 'JAM', label: '牙买加' },
  { value: 'JPN', label: '日本' },
  { value: 'JRSM', label: '耶路撒冷' },
  { value: 'JORD', label: '约旦' },
  { value: 'KAZ', label: '哈萨克斯坦' },
  { value: 'KENY', label: '肯尼亚' },
  { value: 'KIRI', label: '基里巴斯' },
  { value: 'PRK', label: '朝鲜' },
  { value: 'KOR', label: '韩国' },
  { value: 'KSV', label: '科索沃' },
  { value: 'KUWT', label: '科威特' },
  { value: 'KGZ', label: '吉尔吉斯斯坦' },
  { value: 'LAOS', label: '老挝' },
  { value: 'LATV', label: '拉脱维亚' },
  { value: 'LEBN', label: '黎巴嫩' },
  { value: 'LES', label: '莱索托' },
  { value: 'LIBR', label: '利比里亚' },
  { value: 'LBYA', label: '利比亚' },
  { value: 'LCHT', label: '列支敦士登' },
  { value: 'LITH', label: '立陶宛' },
  { value: 'LXM', label: '卢森堡' },
  { value: 'MAC', label: '中国澳门特别行政区' },
  { value: 'MKD', label: '北马其顿' },
  { value: 'MADG', label: '马达加斯加' },
  { value: 'MALW', label: '马拉维' },
  { value: 'MLAS', label: '马来西亚' },
  { value: 'MLDI', label: '马尔登岛' },
  { value: 'MLDV', label: '马尔代夫' },
  { value: 'MALI', label: '马里' },
  { value: 'MLTA', label: '马耳他' },
  { value: 'RMI', label: '马绍尔群岛' },
  { value: 'MAUR', label: '毛里塔尼亚' },
  { value: 'MRTS', label: '毛里求斯' },
  { value: 'MYT', label: '马约特' },
  { value: 'AGS', label: '墨西哥-阿瓜斯卡连特斯' },
  { value: 'BC', label: '墨西哥-下加利福尼亚北部' },
  { value: 'BCSR', label: '墨西哥-下加利福尼亚南部' },
  { value: 'CAMP', label: '墨西哥-坎佩切' },
  { value: 'CHIS', label: '墨西哥-恰帕斯' },
  { value: 'CHIH', label: '墨西哥-奇瓦瓦' },
  { value: 'COAH', label: '墨西哥-科阿韦拉' },
  { value: 'COLI', label: '墨西哥-科利马' },
  { value: 'DF', label: '墨西哥-联邦区' },
  { value: 'DGO', label: '墨西哥-杜兰戈' },
  { value: 'GTO', label: '墨西哥-瓜纳华托' },
  { value: 'GRO', label: '墨西哥-格雷罗' },
  { value: 'HGO', label: '墨西哥-伊达尔戈' },
  { value: 'JAL', label: '墨西哥-哈利斯科' },
  { value: 'MCH', label: '墨西哥-米却肯' },
  { value: 'MOR', label: '墨西哥-莫雷洛斯' },
  { value: 'NAY', label: '墨西哥-纳亚里特' },
  { value: 'NL', label: '墨西哥-新莱昂' },
  { value: 'OAX', label: '墨西哥-瓦哈卡' },
  { value: 'PUE', label: '墨西哥-普埃布拉' },
  { value: 'QRO', label: '墨西哥-克雷塔罗' },
  { value: 'QROO', label: '墨西哥-金塔纳罗奥' },
  { value: 'SLP', label: '墨西哥-圣路易斯波托西' },
  { value: 'SIN', label: '墨西哥-锡那罗亚' },
  { value: 'SON', label: '墨西哥-索诺拉' },
  { value: 'MXCO', label: '墨西哥-墨西哥州' },
  { value: 'TAB', label: '墨西哥-塔巴斯科' },
  { value: 'TAMP', label: '墨西哥-塔毛利帕斯' },
  { value: 'TLAX', label: '墨西哥-特拉斯卡拉' },
  { value: 'VER', label: '墨西哥-韦拉克鲁斯' },
  { value: 'YUC', label: '墨西哥-尤卡坦' },
  { value: 'ZAC', label: '墨西哥-萨卡特卡斯' },
  { value: 'MEX', label: '墨西哥' },
  { value: 'FSM', label: '密克罗尼西亚' },
  { value: 'MDWI', label: '中途岛' },
  { value: 'MLD', label: '摩尔多瓦' },
  { value: 'MON', label: '摩纳哥' },
  { value: 'MONG', label: '蒙古' },
  { value: 'MTG', label: '黑山' },
  { value: 'MONT', label: '蒙特塞拉特' },
  { value: 'MORO', label: '摩洛哥' },
  { value: 'MOZ', label: '莫桑比克' },
  { value: 'NAMB', label: '纳米比亚' },
  { value: 'NAU', label: '瑙鲁' },
  { value: 'NEP', label: '尼泊尔' },
  { value: 'NETH', label: '荷兰' },
  { value: 'NCAL', label: '新喀里多尼亚' },
  { value: 'NZLD', label: '新西兰' },
  { value: 'NIC', label: '尼加拉瓜' },
  { value: 'NIR', label: '尼日尔' },
  { value: 'NRA', label: '尼日利亚' },
  { value: 'NIUE', label: '纽埃' },
  { value: 'NFK', label: '诺福克岛' },
  { value: 'MNP', label: '北马里亚纳群岛' },
  { value: 'NIRE', label: '北爱尔兰' },
  { value: 'NORW', label: '挪威' },
  { value: 'OMAN', label: '阿曼' },
  { value: 'PKST', label: '巴基斯坦' },
  { value: 'PALA', label: '帕劳' },
  { value: 'PLMR', label: '帕尔迈拉环礁' },
  { value: 'PAL', label: '巴勒斯坦' },
  { value: 'PAN', label: '巴拿马' },
  { value: 'PNG', label: '巴布亚新几内亚' },
  { value: 'PARA', label: '巴拉圭' },
  { value: 'PERU', label: '秘鲁' },
  { value: 'PHIL', label: '菲律宾' },
  { value: 'PITC', label: '皮特凯恩群岛' },
  { value: 'POL', label: '波兰' },
  { value: 'PORT', label: '葡萄牙' },
  { value: 'PR', label: '波多黎各' },
  { value: 'QTAR', label: '卡塔尔' },
  { value: 'ROM', label: '罗马尼亚' },
  { value: 'RUS', label: '俄罗斯' },
  { value: 'RWND', label: '卢旺达' },
  { value: 'MAF', label: '圣马丁' },
  { value: 'WSAM', label: '萨摩亚' },
  { value: 'SMAR', label: '圣马力诺' },
  { value: 'STPR', label: '圣多美和普林西比' },
  { value: 'SARB', label: '沙特阿拉伯' },
  { value: 'SENG', label: '塞内加尔' },
  { value: 'SBA', label: '塞尔维亚' },
  { value: 'SEYC', label: '塞舌尔' },
  { value: 'SLEO', label: '塞拉利昂' },
  { value: 'SING', label: '新加坡' },
  { value: 'STM', label: '荷属圣马丁' },
  { value: 'SVK', label: '斯洛伐克' },
  { value: 'SVN', label: '斯洛文尼亚' },
  { value: 'SLMN', label: '所罗门群岛' },
  { value: 'SOMA', label: '索马里' },
  { value: 'SAFR', label: '南非' },
  { value: 'SGS', label: '南乔治亚岛和南桑威奇群岛' },
  { value: 'SSDN', label: '南苏丹' },
  { value: 'SPN', label: '西班牙' },
  { value: 'SRL', label: '斯里兰卡' },
  { value: 'STBR', label: '圣巴泰勒米岛' },
  { value: 'SHEL', label: '圣赫勒拿' },
  { value: 'STCN', label: '圣基茨和尼维斯' },
  { value: 'SLCA', label: '圣卢西亚' },
  { value: 'SPMI', label: '圣皮埃尔和密克隆' },
  { value: 'STVN', label: '圣文森特和格林纳丁斯' },
  { value: 'XXX', label: '无国籍' },
  { value: 'SUDA', label: '苏丹' },
  { value: 'SURM', label: '苏里南' },
  { value: 'SJM', label: '斯瓦尔巴' },
  { value: 'SWDN', label: '瑞典' },
  { value: 'SWTZ', label: '瑞士' },
  { value: 'SYR', label: '叙利亚' },
  { value: 'TWAN', label: '中国台湾' },
  { value: 'TJK', label: '塔吉克斯坦' },
  { value: 'TAZN', label: '坦桑尼亚' },
  { value: 'THAI', label: '泰国' },
  { value: 'TMOR', label: '东帝汶' },
  { value: 'TOGO', label: '多哥' },
  { value: 'TKL', label: '托克劳' },
  { value: 'TONG', label: '汤加' },
  { value: 'TRIN', label: '特立尼达和多巴哥' },
  { value: 'TNSA', label: '突尼斯' },
  { value: 'TRKY', label: '土耳其' },
  { value: 'TKM', label: '土库曼斯坦' },
  { value: 'TCIS', label: '特克斯和凯科斯群岛' },
  { value: 'TUV', label: '图瓦卢' },
  { value: 'UGAN', label: '乌干达' },
  { value: 'UKR', label: '乌克兰' },
  { value: 'UAE', label: '阿联酋' },
  { value: 'GRBR', label: '英国' },
  { value: 'USA', label: '美国' },
  { value: 'URU', label: '乌拉圭' },
  { value: 'UZB', label: '乌兹别克斯坦' },
  { value: 'VANU', label: '瓦努阿图' },
  { value: 'VENZ', label: '委内瑞拉' },
  { value: 'VTNM', label: '越南' },
  { value: 'VI', label: '美属维尔京群岛' },
  { value: 'BRVI', label: '英属维尔京群岛' },
  { value: 'WKI', label: '威克岛' },
  { value: 'WAFT', label: '瓦利斯和富图纳群岛' },
  { value: 'XWB', label: '西岸' },
  { value: 'SSAH', label: '西撒哈拉' },
  { value: 'YEM', label: '也门' },
  { value: 'ZAMB', label: '赞比亚' },
  { value: 'ZIMB', label: '津巴布韦' }
];

// US status options for relatives
export const usStatusOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'S', label: '美国公民' },
  { value: 'C', label: '美国合法永久居民 (LPR)' },
  { value: 'P', label: '非移民' },
  { value: 'O', label: '其他/不知道' }
];

// Relationship options for relatives
export const relationshipOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'S', label: '配偶' },
  { value: 'F', label: '未婚夫/未婚妻' },
  { value: 'C', label: '子女' },
  { value: 'B', label: '兄弟姐妹' }
];

// Length of stay unit options
export const losUnitOptions = [
  { value: '', label: '-请选择一个-' },
  { value: 'Y', label: '年' },
  { value: 'M', label: '月' },
  { value: 'W', label: '周' },
  { value: 'D', label: '天' },
  { value: 'H', label: '少于24小时' },
];

// Helper function to determine if a specific purpose code indicates a dependent relationship
export const isDependentSelection = (value: string): boolean => {
  // List of codes that indicate a dependent relationship (child, spouse, etc.)
  const dependentCodes = [
    'A1-CH', 'A1-SP', 'A2-CH', 'A2-SP', 'A3-CH', 'A3-SP',
    'CW2-CH', 'CW2-SP', 
    'E1-CH', 'E1-SP', 'E2-CH', 'E2-SP', 'E3D-CH', 'E3D-SP',
    'F2-CH', 'F2-SP',
    'G1-CH', 'G1-SP', 'G2-CH', 'G2-SP', 'G3-CH', 'G3-SP', 'G4-CH', 'G4-SP', 'G5-CH', 'G5-SP',
    'H4-CH', 'H4-SP',
    'I-CH', 'I-SP',
    'J2-CH', 'J2-SP',
    'K2-K2', 'K4-K4',
    'L2-CH', 'L2-SP',
    'M2-CH', 'M2-SP',
    'N8-CH',
    'NATO1-SP', 'NATO1-CH', 'NATO2-SP', 'NATO2-CH', 'NATO3-SP', 'NATO3-CH', 
    'NATO4-SP', 'NATO4-CH', 'NATO5-SP', 'NATO5-CH', 'NATO6-SP', 'NATO6-CH',
    'NATO7-SP', 'NATO7-CH',
    'O3-SP', 'O3-CH',
    'P4-SP', 'P4-CH',
    'R2-R2', 'R3-R3',
    'S7-S7',
    'T2-SP', 'T3-CH', 'T4-PR', 'T5-SB', 'T6-CB',
    'TD-SP', 'TD-CH',
    'U2-SP', 'U3-CH', 'U4-PR', 'U5-SB'
  ];
  
  return dependentCodes.includes(value);
};

// Education level options
export const educationLevelOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'NO_EDUCATION', label: '无教育经历' },
  { value: 'PRIMARY', label: '小学' },
  { value: 'SECONDARY', label: '中学' },
  { value: 'HIGH_SCHOOL', label: '高中' },
  { value: 'VOCATIONAL', label: '职业学校' },
  { value: 'ASSOCIATE', label: '大专' },
  { value: 'BACHELOR', label: '本科' },
  { value: 'MASTER', label: '硕士' },
  { value: 'DOCTORAL', label: '博士' },
  { value: 'PROFESSIONAL', label: '专业学位（如医学、法律）' },
  { value: 'OTHER', label: '其他' },
];

// Occupation options for Work/Education/Training section
export const occupationOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'A', label: '农业 (AGRICULTURE)' },
  { value: 'AP', label: '艺术家/表演者 (ARTIST/PERFORMER)' },
  { value: 'B', label: '商业 (BUSINESS)' },
  { value: 'CM', label: '通讯 (COMMUNICATIONS)' },
  { value: 'CS', label: '计算机科学 (COMPUTER SCIENCE)' },
  { value: 'C', label: '烹饪/食品服务 (CULINARY/FOOD SERVICES)' },
  { value: 'ED', label: '教育 (EDUCATION)' },
  { value: 'EN', label: '工程 (ENGINEERING)' },
  { value: 'G', label: '政府 (GOVERNMENT)' },
  { value: 'H', label: '家庭主妇/夫 (HOMEMAKER)' },
  { value: 'LP', label: '法律专业 (LEGAL PROFESSION)' },
  { value: 'MH', label: '医疗/健康 (MEDICAL/HEALTH)' },
  { value: 'M', label: '军事 (MILITARY)' },
  { value: 'NS', label: '自然科学 (NATURAL SCIENCE)' },
  { value: 'N', label: '未就业 (NOT EMPLOYED)' },
  { value: 'PS', label: '物理科学 (PHYSICAL SCIENCES)' },
  { value: 'RV', label: '宗教职业 (RELIGIOUS VOCATION)' },
  { value: 'R', label: '研究 (RESEARCH)' },
  { value: 'RT', label: '退休 (RETIRED)' },
  { value: 'SS', label: '社会科学 (SOCIAL SCIENCE)' },
  { value: 'S', label: '学生 (STUDENT)' },
  { value: 'O', label: '其他 (OTHER)' },
];
