// Format for state dropdown options
export const usStateOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'AL', label: '阿拉巴马' },
  { value: 'AK', label: '阿拉斯加' },
  { value: 'AS', label: '美属萨摩亚' },
  { value: 'AZ', label: '亚利桑那' },
  { value: 'AR', label: '阿肯色' },
  { value: 'CA', label: '加利福尼亚' },
  { value: 'CO', label: '科罗拉多' },
  { value: 'CT', label: '康涅狄格' },
  { value: 'DE', label: '特拉华' },
  { value: 'DC', label: '哥伦比亚特区' },
  { value: 'FL', label: '佛罗里达' },
  { value: 'GA', label: '乔治亚' },
  { value: 'GU', label: '关岛' },
  { value: 'HI', label: '夏威夷' },
  { value: 'ID', label: '爱达荷' },
  { value: 'IL', label: '伊利诺伊' },
  { value: 'IN', label: '印第安纳' },
  { value: 'IA', label: '爱荷华' },
  { value: 'KS', label: '堪萨斯' },
  { value: 'KY', label: '肯塔基' },
  { value: 'LA', label: '路易斯安那' },
  { value: 'ME', label: '缅因' },
  { value: 'MD', label: '马里兰' },
  { value: 'MA', label: '马萨诸塞' },
  { value: 'MI', label: '密歇根' },
  { value: 'MN', label: '明尼苏达' },
  { value: 'MS', label: '密西西比' },
  { value: 'MO', label: '密苏里' },
  { value: 'MT', label: '蒙大拿' },
  { value: 'NE', label: '内布拉斯加' },
  { value: 'NV', label: '内华达' },
  { value: 'NH', label: '新罕布什尔' },
  { value: 'NJ', label: '新泽西' },
  { value: 'NM', label: '新墨西哥' },
  { value: 'NY', label: '纽约' },
  { value: 'NC', label: '北卡罗来纳' },
  { value: 'ND', label: '北达科他' },
  { value: 'MP', label: '北马里亚纳群岛' },
  { value: 'OH', label: '俄亥俄' },
  { value: 'OK', label: '俄克拉荷马' },
  { value: 'OR', label: '俄勒冈' },
  { value: 'PA', label: '宾夕法尼亚' },
  { value: 'PR', label: '波多黎各' },
  { value: 'RI', label: '罗德岛' },
  { value: 'SC', label: '南卡罗来纳' },
  { value: 'SD', label: '南达科他' },
  { value: 'TN', label: '田纳西' },
  { value: 'TX', label: '德克萨斯' },
  { value: 'UT', label: '犹他' },
  { value: 'VT', label: '佛蒙特' },
  { value: 'VI', label: '美属维尔京群岛' },
  { value: 'VA', label: '弗吉尼亚' },
  { value: 'WA', label: '华盛顿' },
  { value: 'WV', label: '西弗吉尼亚' },
  { value: 'WI', label: '威斯康星' },
  { value: 'WY', label: '怀俄明' },
];

// Format for country dropdown options
export const countryOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'AFGH', label: '阿富汗' },
  { value: 'ALB', label: '阿尔巴尼亚' },
  { value: 'ALGR', label: '阿尔及利亚' },
  { value: 'ASMO', label: '美属萨摩亚' },
  { value: 'ANDO', label: '安道尔' },
  { value: 'ANGL', label: '安哥拉' },
  { value: 'ANGU', label: '安圭拉' },
  { value: 'ANTI', label: '安提瓜和巴布达' },
  { value: 'ARG', label: '阿根廷' },
  { value: 'ARM', label: '亚美尼亚' },
  { value: 'ARB', label: '阿鲁巴' },
  { value: 'XAS', label: '海上' },
  { value: 'ASTL', label: '澳大利亚' },
  { value: 'AUST', label: '奥地利' },
  { value: 'AZR', label: '阿塞拜疆' },
  { value: 'BAMA', label: '巴哈马' },
  { value: 'BAHR', label: '巴林' },
  { value: 'BANG', label: '孟加拉国' },
  { value: 'BRDO', label: '巴巴多斯' },
  { value: 'BYS', label: '白俄罗斯' },
  { value: 'BELG', label: '比利时' },
  { value: 'BLZ', label: '伯利兹' },
  { value: 'BENN', label: '贝宁' },
  { value: 'BERM', label: '百慕大' },
  { value: 'BHU', label: '不丹' },
  { value: 'BOL', label: '玻利维亚' },
  { value: 'BIH', label: '波斯尼亚和黑塞哥维那' },
  { value: 'BOT', label: '博茨瓦纳' },
  { value: 'BRZL', label: '巴西' },
  { value: 'BRNI', label: '文莱' },
  { value: 'BULG', label: '保加利亚' },
  { value: 'BURK', label: '布基纳法索' },
  { value: 'BURM', label: '缅甸' },
  { value: 'BRND', label: '布隆迪' },
  { value: 'CBDA', label: '柬埔寨' },
  { value: 'CMRN', label: '喀麦隆' },
  { value: 'CAN', label: '加拿大' },
  { value: 'CAVI', label: '佛得角' },
  { value: 'CAYI', label: '开曼群岛' },
  { value: 'CAFR', label: '中非共和国' },
  { value: 'CHAD', label: '乍得' },
  { value: 'CHIL', label: '智利' },
  { value: 'CHIN', label: '中国' },
  { value: 'HNK', label: '中国香港特别行政区' },
  { value: 'MAC', label: '中国澳门特别行政区' },
  { value: 'TWAN', label: '中国台湾' },
  // ... more countries can be added
];

// US status options for relatives
export const usStatusOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'S', label: '美国公民' },
  { value: 'C', label: '美国合法永久居民 (LPR)' },
  { value: 'P', label: '非移民' },
  { value: 'O', label: '其他/不知道' }
];

// Relationship options for relatives
export const relationshipOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'S', label: '配偶' },
  { value: 'F', label: '未婚夫/未婚妻' },
  { value: 'C', label: '子女' },
  { value: 'B', label: '兄弟姐妹' }
];

// Length of stay unit options
export const losUnitOptions = [
  { value: '', label: '-请选择一个-' },
  { value: 'Y', label: '年' },
  { value: 'M', label: '月' },
  { value: 'W', label: '周' },
  { value: 'D', label: '天' },
  { value: 'H', label: '少于24小时' },
];

// Helper function to determine if a specific purpose code indicates a dependent relationship
export const isDependentSelection = (value: string): boolean => {
  // List of codes that indicate a dependent relationship (child, spouse, etc.)
  const dependentCodes = [
    'A1-CH', 'A1-SP', 'A2-CH', 'A2-SP', 'A3-CH', 'A3-SP',
    'CW2-CH', 'CW2-SP', 
    'E1-CH', 'E1-SP', 'E2-CH', 'E2-SP', 'E3D-CH', 'E3D-SP',
    'F2-CH', 'F2-SP',
    'G1-CH', 'G1-SP', 'G2-CH', 'G2-SP', 'G3-CH', 'G3-SP', 'G4-CH', 'G4-SP', 'G5-CH', 'G5-SP',
    'H4-CH', 'H4-SP',
    'I-CH', 'I-SP',
    'J2-CH', 'J2-SP',
    'K2-K2', 'K4-K4',
    'L2-CH', 'L2-SP',
    'M2-CH', 'M2-SP',
    'N8-CH',
    'NATO1-SP', 'NATO1-CH', 'NATO2-SP', 'NATO2-CH', 'NATO3-SP', 'NATO3-CH', 
    'NATO4-SP', 'NATO4-CH', 'NATO5-SP', 'NATO5-CH', 'NATO6-SP', 'NATO6-CH',
    'NATO7-SP', 'NATO7-CH',
    'O3-SP', 'O3-CH',
    'P4-SP', 'P4-CH',
    'R2-R2', 'R3-R3',
    'S7-S7',
    'T2-SP', 'T3-CH', 'T4-PR', 'T5-SB', 'T6-CB',
    'TD-SP', 'TD-CH',
    'U2-SP', 'U3-CH', 'U4-PR', 'U5-SB'
  ];
  
  return dependentCodes.includes(value);
};

// Education level options
export const educationLevelOptions = [
  { value: '', label: '- 请选择一个 -' },
  { value: 'NO_EDUCATION', label: '无教育经历' },
  { value: 'PRIMARY', label: '小学' },
  { value: 'SECONDARY', label: '中学' },
  { value: 'HIGH_SCHOOL', label: '高中' },
  { value: 'VOCATIONAL', label: '职业学校' },
  { value: 'ASSOCIATE', label: '大专' },
  { value: 'BACHELOR', label: '本科' },
  { value: 'MASTER', label: '硕士' },
  { value: 'DOCTORAL', label: '博士' },
  { value: 'PROFESSIONAL', label: '专业学位（如医学、法律）' },
  { value: 'OTHER', label: '其他' },
];
